CREATE TABLE IF NOT EXISTS regions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    game_id INT NOT NULL,
    region_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    compact_name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (game_id, region_id),
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

